video: 'inputs/people_mall.mp4'
config: 'configs/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb.py'
checkpoint: 'https://download.openmmlab.com/mmaction/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb/slowfast_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb-b987b516.pth'
det-config: 'configs/human_detection/yolov3_mobilenetv2_mstrain-416_300e_coco.py'
det-checkpoint: 'https://download.openmmlab.com/mmdetection/v2.0/yolo/yolov3_mobilenetv2_mstrain-416_300e_coco/yolov3_mobilenetv2_mstrain-416_300e_coco_20210718_010823-f68a07b3.pth'
det-score-thr: 0.3
action-score-thr: 0.3
label-map: 'tools/data/ava/label_map.txt'
predict-stepsize: 8 # default val from mmaction2
output-stepsize: 4 # default val from mmaction2
output-fps: 6 # default val from mmaction2
out-filename: 'outputs/people_mall.mp4'
device: 'cpu'